### ISSUE TITLE
[week4] week1 ~ week3 안 푼 문제 todo

### ISSUE THREAD

**Issue by kyukong** [kyukong/SeSAC-Algo#22]
- [ ] [5427 불](https://www.acmicpc.net/problem/5427)
- [ ] [2212 센서](https://www.acmicpc.net/problem/2212)
- [ ] [17135 캐슬 디펜스](https://www.acmicpc.net/problem/17135)
- [ ] [19236 청소년 상어](https://www.acmicpc.net/problem/19236)
- [ ] [1707 이분 그래프](https://www.acmicpc.net/problem/1707)
